version: "3.7"

services:

  webserver:
    build:
      context: ./bin/webserver
    image: custom/openlitespeed
    container_name: "ols-openlitespeed"
    restart: "always"
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:9001"
      - "${HOST_MACHINE_SECURE_HOST_PORT}:443"
      - 7080:7080
    volumes:
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${OPENLITESPEED_CONFIG-./config/openlitespeed-config/httpd_config.conf}:/usr/local/lsws/conf/httpd_config.conf
      - ${OPENLITESPEED_VHOST-./config/openlitespeed-vhosts/vhconf.conf}:/usr/local/lsws/conf/vhosts/Example/vhconf.conf
      - ${DOCKER_CONFIG-./config/openlitespeed-docker/docker.conf}:/usr/local/lsws/conf/templates/docker.conf
      - ${LOG_DIR-./logs/openlitespeed}:/usr/local/lsws/logs/
      - ./web_bir:/var/www/vhosts/localhost/html/
    depends_on:
      - olsdb

  olsdb:
    image: mariadb
    container_name: ols-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: okay
      MYSQL_PASSWORD: 1234
    volumes:
      - ./data/db:/var/lib/mysql

  phpmyadmin:
    build:
      context: ./bin/phpmyadmin
    image: custom/phpmyadmin
    container_name: "ols-phpmyadmin"
    environment:
      PMA_HOST: olsdb
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: 1234
      UPLOAD_LIMIT: 500M
    ports:
      - "${PHPMYADMIN_PORT}:80"
    depends_on:
      - olsdb
